### PR TITLE
Fix LED status on certain Razer laptops

### LINKED ISSUE #413: Cannot control Logo LED on new Razer laptops
The logo LED on the Blade Pro 2017 seems to act a bit oddly.

Writing `0` to `/sys/bus/hid/drivers/razerkbd/[...]/logo_led_state` will set the LED to on. 

Writing `1` will result the following log entry in dmesg, and will set the LED state to on similar to `0`:

    razerkbd: Command not supported. Start Marker: 05 id: ff Num Params: 03 Reserved: 03 Command: 02 Params: 01040100000000000000000000000000 .

Writing `2` will result in the LED pulsating similar to a sleep mode.

### PR DESCRIPTION
**Pull request by KazWolfe**
- Remove Razer Blade Pro 2017 from inverted LEDs list
- Update code so that laptops use state instead of effect for
  lights.

Should fix #413.

**Note:** Was not tested yet!

### CODE REVIEW

File: driver/razerkbd_driver.c [hunk 1]
```diff
@@ -1040,9 +1040,9 @@ static ssize_t razer_attr_read_set_logo(struct device *dev, struct device_attrib
     struct usb_interface *intf = to_usb_interface(dev->parent);
     struct usb_device *usb_dev = interface_to_usbdev(intf);
     struct razer_report report = razer_chroma_standard_get_led_effect(VARSTORE, LOGO_LED);
-    struct razer_report response;  
+    struct razer_report response;
     int state;
-
```
Comment (z3ntu) [inline driver/razerkbd_driver.c]: everybody should care about whitespaces in empty lines because it's baaaad

File: driver/razerkbd_driver.c [hunk 2]
```diff
@@ -1040,9 +1040,9 @@ static ssize_t razer_attr_read_set_logo(struct device *dev, struct device_attrib
     struct usb_interface *intf = to_usb_interface(dev->parent);
     struct usb_device *usb_dev = interface_to_usbdev(intf);
     struct razer_report report = razer_chroma_standard_get_led_effect(VARSTORE, LOGO_LED);
-    struct razer_report response;
```
Comment (z3ntu) [inline driver/razerkbd_driver.c]: and here you left 2 spaces at the end of the line ^^

Comment (KazWolfe) [reply driver/razerkbd_driver.c]: ah. i'll just go blame gedit for both. i should really install clion at some point.

File: driver/razerkbd_driver.c (hunk 1 above)
Comment (KazWolfe) [reply driver/razerkbd_driver.c]: but are they? 🤔

Comment (z3ntu) [reply driver/razerkbd_driver.c]: yes 😄
