### PR TITLE
Razer Naga 2014 REL_HWHEEL event support

### LINKED ISSUE #1557: Wrong Input events emited (`REL_WHEEL` instead of `REL_HWHEEL`)
### Distribution
```
Distributor ID:	Ubuntu
Description:	Ubuntu 21.04
Release:	21.04
Codename:	hirsute
```

### Support

- [X] Have you tried rebooting?
- [X] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

I was doing some work with `libevdev` and noticed that I was unable to create horizontal wheel events with my device and instead it would create vertical wheel events.

below is one leftwards scroll click (3 events) and 3 downwards scroll detents (1 event each).
```
sudo evtest /dev/input/by-id/usb-Razer_Razer_Naga_2014-event-mouse 
Input driver version is 1.0.1
Input device ID: bus 0x3 vendor 0x1532 product 0x40 version 0x111
Input device name: "Razer Razer Naga 2014"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 272 (BTN_LEFT)
    Event code 273 (BTN_RIGHT)
    Event code 274 (BTN_MIDDLE)
    Event code 275 (BTN_SIDE)
    Event code 276 (BTN_EXTRA)
  Event type 2 (EV_REL)
    Event code 0 (REL_X)
    Event code 1 (REL_Y)
    Event code 8 (REL_WHEEL)
    Event code 11 (REL_WHEEL_HI_RES)
  Event type 4 (EV_MSC)
    Event code 4 (MSC_SCAN)
Properties:
Testing ... (interrupt to exit)
Event: time 1626260186.084732, type 2 (EV_REL), code 8 (REL_WHEEL), value -1
Event: time 1626260186.084732, type 2 (EV_REL), code 11 (REL_WHEEL_HI_RES), value -120
Event: time 1626260186.084732, -------------- SYN_REPORT ------------
Event: time 1626260186.135062, type 2 (EV_REL), code 8 (REL_WHEEL), value -1
Event: time 1626260186.135062, type 2 (EV_REL), code 11 (REL_WHEEL_HI_RES), value -120
Event: time 1626260186.135062, -------------- SYN_REPORT ------------
Event: time 1626260186.184612, type 2 (EV_REL), code 8 (REL_WHEEL), value -1
Event: time 1626260186.184612, type 2 (EV_REL), code 11 (REL_WHEEL_HI_RES), value -120
Event: time 1626260186.184612, -------------- SYN_REPORT ------------
Event: time 1626260187.035039, type 2 (EV_REL), code 8 (REL_WHEEL), value -1
Event: time 1626260187.035039, type 2 (EV_REL), code 11 (REL_WHEEL_HI_RES), value -120
Event: time 1626260187.035039, -------------- SYN_REPORT ------------
Event: time 1626260187.825604, type 2 (EV_REL), code 8 (REL_WHEEL), value -1
Event: time 1626260187.825604, type 2 (EV_REL), code 11 (REL_WHEEL_HI_RES), value -120
Event: time 1626260187.825604, -------------- SYN_REPORT ------------
Event: time 1626260188.061599, type 2 (EV_REL), code 8 (REL_WHEEL), value -1
Event: time 1626260188.061599, type 2 (EV_REL), code 11 (REL_WHEEL_HI_RES), value -120
Event: time 1626260188.061599, -------------- SYN_REPORT ------------
```
but as you can see their all just downward scroll events.

As an attempt to get further understanding, I tried the mouse in "Driver Mode" instead of "Normal Mode", but [as expected](https://github.com/openrazer/openrazer/issues/201) it just disabled all events from the horizontal wheel movement.

Any help or guidance on where I might look for creating a patch for this would be appreciated.

### PR DESCRIPTION
**Pull request by G-M0N3Y-2503**
After some debugging, it looks like the horizontal scroll/wheel tilt events captured for the Basilisk are the same for the Naga 2014. So simple matching my device was enough.

While I was there I figured that I'd add the REL_HWHEEL_HI_RES event to better round out the implementation to match other mice.

Closes https://github.com/openrazer/openrazer/issues/1557

### CODE REVIEW

**Comment by G-M0N3Y-2503** [comment]
Hmmm, not sure why the CI is failing, that check seemed to work in my tests...

Also, not sure how to PR for the Wiki, but I made https://github.com/G-M0N3Y-2503/openrazer/wiki/Debugging-with-KGDB-on-a-QEMU-KVM with all the stuff I need to learn to debug the driver for this.

File: driver/razermouse_driver.c [hunk 1]
```diff
@@ -3680,6 +3680,8 @@ static DEVICE_ATTR(backlight_led_state,            0660, razer_attr_read_backlig
 #define BIT_TILT_L 5
 #define BIT_TILT_R 6
 
+#define SCROLL_DETENT 120
```
Comment (z3ntu) [inline driver/razermouse_driver.c]: What's this magic value?

Comment (G-M0N3Y-2503) [reply driver/razermouse_driver.c]: > The accumulated value 120 represents movement by one detent

https://www.kernel.org/doc/html/latest/input/event-codes.html#ev-rel

Comment (z3ntu) [reply driver/razermouse_driver.c]: Why are we pretending to have high-resolution scrolling support now though? Afaik we don't get smaller increments from the hardware so there's not really a point in pretending?

Comment (G-M0N3Y-2503) [reply driver/razermouse_driver.c]: mostly just added it because the generic HID driver reports these events for the same hardware.  The same goes for the Logitech mouse I have and its driver, despite it also not reporting anything other than +/-120.   
Figured if some piece of software was expecting these events instead of both it'd work around their bug.

I don't mind removing that commit if you'd prefer though.

Comment (G-M0N3Y-2503) [reply driver/razermouse_driver.c]: Looked into this a little bit more and it [looks like just the `REL_WHEEL_HI_RES` event is configured in the default HID driver](https://github.com/torvalds/linux/blob/master/drivers/hid/hid-input.c#L750), Then [it calculates the `REL_WHEEL` from the `REL_WHEEL_HI_RES` and emits both events](https://github.com/torvalds/linux/blob/master/drivers/hid/hid-input.c#L1309). This seems to work as it appears that Windows sets the expectation of 120 per detent from the hardware.

Comment (G-M0N3Y-2503) [reply driver/razermouse_driver.c]: I removed this contentious part of this PR for a later one

Comment (z3ntu) [reply driver/razermouse_driver.c]: Thanks

**Review by z3ntu — APPROVED** [review]
Looks sane now, thanks!
