### PR TITLE
Use different profile LED IDs for some keypads

### LINKED ISSUE #1089: Profile LEDs not correct for Orbweaver Chroma
The profile LEDs for the Orbweaver Chroma should be remapped as they all hit the wrong stuff:

Currently:

```
profile_led_green -> blue led
profile_led_red   -> green led
profile_led_blue  -> yellow led
```

Should be:

```
profile_led_green -> greed led
profile_led_red   -> yellow led
profile_led_blue  -> blue led
```

I've identified the culprit: 

https://github.com/openrazer/openrazer/blob/3592f8197dc2bd143f02a5f996ba8f6feb9b7f80/driver/razercommon.h#L52-L54

As these are hardcoded (and because this was originally written for the Tatarus), there's doesn't seem to be a super easy way out.

### PR DESCRIPTION
**Pull request by lah7**
Fixes #1089. This commit fixes the wrong keypad profile LEDs on the Tartarus Chroma and Orbweaver Chroma.

It would be useful to know if this alternate ID is needed for other keypads, or just the ones that were  originally added (in which case, [Orbweaver may need to be added](https://github.com/openrazer/openrazer/commit/86af64a8f3d11a13dd09be37a26069b1998855b4#diff-04c6e90faac2675aa89e2176d2eec7d8L72-L76))

#### Devices to be checked

- [x] ~~Nostromo~~ (OK - https://github.com/openrazer/openrazer/commit/86af64a8f3d11a13dd09be37a26069b1998855b4#diff-6f38cc63b8755079814e6aa5d740b081L47-L49)
- [ ] Tartarus
- [x] Tartarus Chroma
- [ ] Tartarus V2
- [ ] Orbweaver
- [x] Orbweaver Chroma

### CODE REVIEW

**Comment by chabad360** [comment]
Thanks.

Wouldn't it be better to just reuse the existing constants instead of defining new ones?

File: driver/razerkbd_driver.c [hunk 1]
```diff
@@ -653,6 +653,14 @@ static ssize_t razer_attr_read_tartarus_profile_led_red(struct device *dev, stru
...
     struct razer_report report = razer_chroma_standard_get_led_state(VARSTORE, RED_PROFILE_LED);
+
+    switch(usb_dev->descriptor.idProduct) {
+    case USB_DEVICE_ID_RAZER_ORBWEAVER_CHROMA:
+    case USB_DEVICE_ID_RAZER_TARTARUS_CHROMA:
+        report = razer_chroma_standard_get_led_state(VARSTORE, ALTERNATE_RED_PROFILE_LED);
+        break;
+    }
+
     struct razer_report response = razer_send_payload(usb_dev, &report);
```
Comment (chabad360) [inline driver/razerkbd_driver.c]: Move the declaration of `response` to before the switch. It should fix the CI errors.

**Comment by lah7** [comment]
Thanks for the review - made changes and tested again

File: driver/razercommon.h [hunk 2]
```diff
@@ -55,10 +55,10 @@ do { \
 #define RIGHT_SIDE_LED    0x10
 #define LEFT_SIDE_LED     0x11
 
-// Some keypads have different profile LED IDs
-#define ALTERNATE_RED_PROFILE_LED   0x0E
-#define ALTERNATE_GREEN_PROFILE_LED 0x0C
-#define ALTERNATE_BLUE_PROFILE_LED  0x0D
+// Some keypads have different profile LED IDs mapped
+#define ALTERNATE_RED_PROFILE_LED   BLUE_PROFILE_LED
```
Comment (chabad360) [inline driver/razercommon.h]: Wasn't what I had in mind, but ok... I guess the intention is more clear.

Comment (lah7) [reply driver/razercommon.h]: I see... well, it could be done like this or just inside the `switch`, not too fused. The maintainer who clicks the Merge button can have the final say. :wink:

I originally thought to use an "alternate" variable so it's pretty obvious later that a certain range of Razer keypads followed a different "spec" / wiring. Someone poking through the source code could mistakenly assume these are the "correct" definitions for all keypads. Plus, I didn't want the `red` function referring the `blue` twice (get/set) since it confuses me enough. :sweat_smile:

Comment (chabad360) [reply driver/razercommon.h]: Fair enough.

File: driver/razerkbd_driver.c [hunk 3]
```diff
@@ -652,8 +652,20 @@ static ssize_t razer_attr_read_tartarus_profile_led_red(struct device *dev, stru
...
     struct usb_device *usb_dev = interface_to_usbdev(intf);
-    struct razer_report report = razer_chroma_standard_get_led_state(VARSTORE, RED_PROFILE_LED);
-    struct razer_report response = razer_send_payload(usb_dev, &report);
+    struct razer_report report = {0};
+    struct razer_report response = {0};
+
+    switch(usb_dev->descriptor.idProduct) {
+    case USB_DEVICE_ID_RAZER_ORBWEAVER_CHROMA:
+    case USB_DEVICE_ID_RAZER_TARTARUS_CHROMA:
+        report = razer_chroma_standard_get_led_state(VARSTORE, ALTERNATE_RED_PROFILE_LED);
```
Comment (z3ntu) [inline driver/razerkbd_driver.c]: I would just put `BLUE_PROFILE_LED` here and not hide it behind another macro :)

Comment (lah7) [reply driver/razerkbd_driver.c]: Okay, the `ALTERNATE_` constant has been ditched. :ok_hand:

**Review by z3ntu — APPROVED** [review]
LGTM, thanks!
