### PR TITLE
Add support for Razer Tartarus Pro (1532:0244) with stability fixes

### LINKED ISSUE #1039: Support for Tartarus Pro (1532:0244)
### Device Info

* Name: Razer Tartarus Pro
* Product Number: RZ07-03110100
* Model Number: RZ07-0311

### Device Information
```
Bus 001 Device 004: ID 1532:0244 Razer USA, Ltd 
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x0244 
  bcdDevice            2.00
  iManufacturer           1 
  iProduct                2 
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0054
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     186
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0018  1x 24 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
```

```
lrwxrwxrwx 1 root root  10 Mar  3 14:54 usb-Razer_Razer_Tartarus_Pro-event-if01 -> ../event28
lrwxrwxrwx 1 root root  10 Mar  3 14:54 usb-Razer_Razer_Tartarus_Pro-event-kbd -> ../event25
lrwxrwxrwx 1 root root  10 Mar  3 14:54 usb-Razer_Razer_Tartarus_Pro-if01-event-kbd -> ../event26
lrwxrwxrwx 1 root root  10 Mar  3 14:54 usb-Razer_Razer_Tartarus_Pro-if02-event-mouse -> ../event30
lrwxrwxrwx 1 root root   9 Mar  3 14:54 usb-Razer_Razer_Tartarus_Pro-if02-mouse -> ../mouse1
```
### Packet Captures

<Please see here as we probably need packet captures>
<https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol>

### Synapse Screenshots
<Screenshots of all available options as seen on Razer Synapse>
Setup is the same as the Tartarus Chroma, I don't have a screenshot but it is the exact same layout so I suspect that a copy pasta of the Chroma code would be a good place to start. 100% willing to run some tests. will start reading up on the above capture packets.

### PR DESCRIPTION
**Pull request by countgitmick**
## Summary

Adds support for the Razer Tartarus Pro keypad (USB ID 1532:0244), including two critical stability fixes that prevent the device from crashing on connect.

Based on initial work by @plxty in #2336.

### New device support
- `driver/razerkbd_driver.c`: HID entries, sysfs attributes for keys and lighting
- `daemon/openrazer_daemon/hardware/keyboards.py`: `RazerTartarusPro` class with full method support

### Bug fix 1: Daemon crash on device detection

**Root cause**: `_MacroKeyboard` sets `DRIVER_MODE = True`, which causes the daemon to send `set_device_mode(0x03, 0x00)` on detection. The Tartarus Pro firmware does not support this command and resets the device, causing an infinite reconnect loop.

**Fix**: `DRIVER_MODE = False` in the `RazerTartarusPro` class.

### Bug fix 2: Kernel probe crash

**Root cause**: The probe function unconditionally calls `razer_set_device_mode(dev, 0x00, 0x00)` for `USB_INTERFACE_PROTOCOL_NONE` devices. The Tartarus Pro firmware resets when it receives this command during probe.

**Fix**: Skip the call for `USB_DEVICE_ID_RAZER_TARTARUS_PRO`.

## Testing

Verified on hardware (Tartarus Pro, USB 1532:0244):
- Device connects without kernel crash or daemon reset loop
- All keys generate correct keycodes
- Static and reactive lighting effects work
- Custom frame (1×21 keys) works correctly

Fixes #1039

### CODE REVIEW

**Comment by z3ntu** [comment]
There's already an open PR for this device: #2622

**Comment by countgitmick** [comment]
Aware of #2622 — it currently has merge conflicts, failing CI (broken indentation), and some issues flagged in review (incorrect battery support, copy-pasted Tartarus V2 class, dead URL). It also doesn't address the two firmware crash bugs (daemon reset loop from `set_device_mode` and kernel probe crash) that this PR fixes. Tested on hardware.

File: driver/razerchromacommon.c [hunk 1]
```diff
@@ -475,6 +475,31 @@ struct razer_report razer_chroma_standard_matrix_set_custom_frame(unsigned char
...
+/**
+ * Get the device's "Static" effect state
+ */
+struct razer_report razer_chroma_extended_matrix_get_effect_static(unsigned char variable_storage, unsigned char led_id)
+{
+    struct razer_report report = razer_chroma_extended_matrix_get_effect_base(0x09, variable_storage, led_id, 0x01);
+
+    report.arguments[5] = 0x01;
+    return report;
+}
```
Comment (z3ntu) [inline driver/razerchromacommon.c]: So this will return the arguments that were set for the static effect? So the colors that were set?

What happens if the device is not on "static"? This needs some documentation.

File: driver/razerchromacommon.c [hunk 2]
```diff
@@ -475,6 +475,31 @@ struct razer_report razer_chroma_standard_matrix_set_custom_frame(unsigned char
...
+/**
+ * Gets the state from extended matrix effect payload
+ */
+static struct razer_report razer_chroma_extended_matrix_get_effect_base(unsigned char arg_size, unsigned char variable_storage, unsigned char led_id, unsigned char effect_id)
+{
+    struct razer_report report = get_razer_report(0x0F, 0x82, arg_size);
+
+    report.arguments[0] = variable_storage;
+    report.arguments[1] = led_id;
+    report.arguments[2] = effect_id; // Effect ID
```
Comment (z3ntu) [inline driver/razerchromacommon.c]: no need for the comment on that line, the variable name literally says that

File: driver/razerkbd_driver.c [hunk 3]
```diff
@@ -14,9 +14,9 @@
 
 #include "usb_hid_keys.h"
 
-#include "razerkbd_driver.h"
 #include "razercommon.h"
 #include "razerchromacommon.h"
+#include "razerkbd_driver.h"
```
Comment (z3ntu) [inline driver/razerkbd_driver.c]: keep this as it was, unless you have a good reason

File: driver/razerkbd_driver.c [hunk 4]
```diff
@@ -1778,13 +1785,19 @@ static ssize_t razer_attr_read_profile_led_red(struct device *dev, struct device
...
+    int red_index = 2;
 
     switch (device->usb_pid) {
     case USB_DEVICE_ID_RAZER_ORBWEAVER_CHROMA:
     case USB_DEVICE_ID_RAZER_TARTARUS_CHROMA:
         request = razer_chroma_standard_get_led_state(VARSTORE, BLUE_PROFILE_LED);
         request.transaction_id.id = 0xFF;
         break;
+    case USB_DEVICE_ID_RAZER_TARTARUS_PRO:
+        request = razer_chroma_extended_matrix_get_effect_static(VARSTORE, SIDE_STRIPE_LED);
```
Comment (z3ntu) [inline driver/razerkbd_driver.c]: I'm not happy doing some wrappers in the driver to hide the fact that it's using a different API underneath, and forcing it to this profile_led_* API. 

Just to confirm, this will control 3 individual red, green and blue LEDs on the Tartarus Pro? Not one RGB LED?

Image

File: driver/razerkbd_driver.c [hunk 5]
```diff
@@ -1892,6 +1917,11 @@ static ssize_t razer_attr_write_profile_led_red(struct device *dev, struct devic
         request = razer_chroma_standard_set_led_state(VARSTORE, BLUE_PROFILE_LED, enabled);
         request.transaction_id.id = 0xFF;
         break;
+    case USB_DEVICE_ID_RAZER_TARTARUS_PRO:
+        device->led_state.r = enabled;
```
Comment (z3ntu) [inline driver/razerkbd_driver.c]: So this device does not work 0-255 brightness, but 0=off, 1=on?

File: driver/razerkbd_driver.c [hunk 6]
```diff
@@ -4084,6 +4134,26 @@ static ssize_t razer_attr_write_matrix_custom_frame(struct device *dev, struct d
...
+            // 16 17 18 19 SCROLL 20
+            if (row_id <= 2) {
+                if (start_col >= 5)
+                    break;
+                if (stop_col >= 5)
+                    stop_col = 4;
+            }
+            start_col += row_id * 5;
+            stop_col += start_col;
+            row_id = 0;
```
Comment (z3ntu) [inline driver/razerkbd_driver.c]: Don't fake this please, just pass through the parameters, and set the matrix as it actually is in the daemon.

Applications using it need to take care that they have the correct layout in their programming. We have plenty of devices that have single-row matrixes that are physically not in a single row

File: driver/razerkbd_driver.c [hunk 7]
```diff
@@ -5395,7 +5480,10 @@ static int razer_kbd_probe(struct hid_device *hdev, const struct hid_device_id *
 
         // Set device to regular mode, not driver mode
         // When the daemon discovers the device it will instruct it to enter driver mode
-        razer_set_device_mode(dev, 0x00, 0x00);
+        // Tartarus Pro firmware does not support this command and will reset if sent
+        if (usb_dev->descriptor.idProduct != USB_DEVICE_ID_RAZER_TARTARUS_PRO) {
```
Comment (z3ntu) [inline driver/razerkbd_driver.c:5477]: That's sad. But I guess the comment "does not support" is not quite right, the firmware knows the command, but it just does bad stuff with it. So just keep the other part of the comment

File: driver/razerkbd_driver.c [hunk 8]
```diff
@@ -1837,7 +1856,7 @@ static ssize_t razer_attr_read_profile_led_green(struct device *dev, struct devi
 
     razer_send_payload(device, &request, &response);
 
-    return sprintf(buf, "%d\n", response.arguments[2]);
+    return sprintf(buf, "%d\n", clamp_u8(response.arguments[green_index], 0, 1));
```
Comment (z3ntu) [inline driver/razerkbd_driver.c]: Are we not just getting 0 & 1 back from the firmware? Why do we need to clamp it?

**Comment by z3ntu** [comment]
I looked back at #2336 and seems you basically stole those commits and didn't attribute any authorship? That's really not okay! Please fix that, otherwise I won't accept this PR.

**Comment by countgitmick** [comment]
This builds on plxty's work in #2336. Should have been credited upfront, apologies. Will update the PR to reflect that.

File: driver/razerkbd_driver.c (hunk 4 above)
Comment (countgitmick) [reply driver/razerkbd_driver.c]: Yes, 3 individual single color LEDs (red, green, blue) for profile indication. Binary on/off. The firmware exposes them as R/G/B channels of SIDE_STRIPE_LED (0x0B) via extended matrix protocol. Will drop the profile LED wrapping for this PR and focus on core device support. Side stripe LED control can be added in the future.

**Comment by z3ntu** [comment]
Okay, I've squashed the commits now and added back some Co-Authored-By tags from #2336 

So essentially this looks fine to me now, can you give it one last check to confirm everything works as expected?

And like you've written in https://github.com/openrazer/openrazer/pull/2710#discussion_r2916066424, I'm looking forward to a follow-up PR implementing support for the profile LEDs!

**Comment by countgitmick** [comment]
Tested on hardware — everything works as expected. Keys, lighting effects, and custom frame all good. Thanks for cleaning up the commits!

**Review by z3ntu — APPROVED** [review]
LGTM, thanks for being the one to get this PR into shape!
